import type { User } from "../db/user";
import type { ErrorCodeType, ErrorCodeMappingValue } from "./errors";

export enum OpCode {
    AUTH_LOGIN = 0,
    AUTH_REGISTER = 1,
    AUTH_SUCCESS = 2,
    AUTH_FAILURE = 3,
    AUTH_REFRESH = 4,
    AUTH_REFRESH_SUCCESS = 5,
    AUTH_LOGOUT = 6,
    ERROR = 7,
    REQUEST_CREATE = 8,
    REQUEST_LIST = 9,
    TAG_CREATE = 10,
    TAG_SET_DEFAULT = 11,
    REQUEST_ASSIGN_TAG = 12,
    LAB_CREATE = 13,
    LAB_UPDATE = 14,
    LAB_DELETE = 15,
    ROLE_CREATE = 16,
    MEMBER_ADD = 17,
    MEMBER_REMOVE = 18,
}

// Generic type for WebSocket payloads
export type OpCodeType = keyof typeof OpCode;
export type OpCodeValue = typeof OpCode[OpCodeType];

export interface OpCodePayload<T extends OpCodeValue> {
    op: T;
    d: any;
}

/**
 * Mapped type that creates a generic payload type for every possible OpCodeValue.
 *
 * Use if you want a mapping from each OpCode to generic payload structure (not the specific payloads).
 */
export type OpCodePayloads = {
    [K in OpCodeValue]: OpCodePayload<K>;
};

/**
 * Similar to OpCodePayloads, but with a conditional type that only includes keys present in OpCodePayloads.
 *
 * Useful if you want to filter or narrow down payloads for only certain OpCodes.
 */
export type OpCodePayloadMap = {
    [K in OpCodeValue]: K extends keyof OpCodePayloads ? OpCodePayloads[K] : never;
};

/**
 * A union type of all possible payloads generated by OpCodePayloadMap.
 *
 * Use if you want a type that represents ANY POSSIBLE payload for ANY opcode (eg a generic message handler)
 */
export type OpCodePayloadUnion = OpCodePayloadMap[OpCodeValue];


/**
 * Login/Register request.
 *
 * - CLIENT -> SERVER when logging in or registering.
 **/
export interface AuthLoginPayload extends OpCodePayload<OpCode.AUTH_LOGIN> {
    d: { email: string; password: string };
}

export interface AuthRegisterPayload extends OpCodePayload<OpCode.AUTH_REGISTER> {
    d: { email: string; password: string; name: string };
}

export type AuthRequestPayload = AuthLoginPayload | AuthRegisterPayload;

/**
 * Success response when logging in or registering.
 *
 * - SERVER -> CLIENT when login/register is successful.
 */
export interface AuthSuccessPayload extends OpCodePayload<OpCode.AUTH_SUCCESS> {
    d: { accessToken: string; refreshToken: string; user: User };
}

/**
 * Failure response when login/register fails.
 *
 * - SERVER -> CLIENT when login/register fails.
 */
export interface AuthFailurePayload extends OpCodePayload<OpCode.AUTH_FAILURE> {
    d: { reason: string };
}
/**
 * Refresh request of an access toke using a refresh token.
 *
 * - CLIENT -> SERVER when refreshing the access token.
 */
export interface AuthRefreshPayload extends OpCodePayload<OpCode.AUTH_REFRESH> {
    d: { refreshToken: string };
}

/**
 * Success response when refreshing the access token.
 *
 * - SERVER -> CLIENT when refresh is successful.
 */
export interface AuthRefreshSuccessPayload extends OpCodePayload<OpCode.AUTH_REFRESH_SUCCESS> {
    d: { accessToken: string; refreshToken: string };
}

// Logs out the user and invalidates the refresh token.

// - CLIENT -> SERVER when logging out.
export interface AuthLogoutPayload extends OpCodePayload<OpCode.AUTH_LOGOUT> {
    d: { refreshToken: string };
}

/**
 * Denotes any error response from the server.
 */

export interface ErrorPayload<E extends ErrorCodeType> extends OpCodePayload<OpCode.ERROR> {
    d: { error: E; response: ErrorCodeMappingValue };
}

export interface RequestCreatePayload extends OpCodePayload<OpCode.REQUEST_CREATE> {
    d: { labId: number; file: string; metadata: any; description?: string; token: string };
}
export interface RequestListPayload extends OpCodePayload<OpCode.REQUEST_LIST> {
    d: { labId: number; token: string };
}
export interface TagCreatePayload extends OpCodePayload<OpCode.TAG_CREATE> {
    d: { labId: number; name: string; isDefault?: boolean; token: string };
}
export interface TagSetDefaultPayload extends OpCodePayload<OpCode.TAG_SET_DEFAULT> {
    d: { tagId: number; isDefault: boolean; token: string };
}
export interface RequestAssignTagPayload extends OpCodePayload<OpCode.REQUEST_ASSIGN_TAG> {
    d: { requestId: number; tagId: number; assign: boolean; token: string };
}

export interface LabCreatePayload extends OpCodePayload<OpCode.LAB_CREATE> {
    d: { name: string; description?: string | null; imageUrl?: string | null; token: string };
}
export interface LabUpdatePayload extends OpCodePayload<OpCode.LAB_UPDATE> {
    d: { labId: number; name: string; description?: string | null; imageUrl?: string | null; token: string };
}
export interface LabDeletePayload extends OpCodePayload<OpCode.LAB_DELETE> {
    d: { labId: number; token: string };
}
export interface RoleCreatePayload extends OpCodePayload<OpCode.ROLE_CREATE> {
    d: { labId: number; name: string; permissions: number; token: string };
}
export interface MemberAddPayload extends OpCodePayload<OpCode.MEMBER_ADD> {
    d: { labId: number; userId: number; roleId: number | null; token: string };
}
export interface MemberRemovePayload extends OpCodePayload<OpCode.MEMBER_REMOVE> {
    d: { labId: number; userId: number; token: string };
}

